liip_imagine:

    resolvers:
        default:
            web_path: ~

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null

    filter_sets:

        thumb_97x97 :
            quality : 75
            filters :
                thumbnail  : { size : [97, 97], mode : outbound }

        # name our filter set "my_watermark_filter"
        my_watermark_filter:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: "Resources/watermark.png"
                    # size of the water mark relative to the input image
                    size: 0.2
                    # set the position of the watermark
                    position: bottomright