#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
logout:
    path: /logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
